name: CI/CD Staging

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências Backend
        run: |
          cd backend
          npm install

      - name: Instalar dependências Frontend
        run: |
          cd frontend
          npm install

      - name: Rodar testes
        run: |
          cd backend
          npm test || echo "sem testes configurados"

      # Aqui entrariam os steps de deploy
      # Exemplo: deploy no Vercel ou Railway
